name: jozz_events
description: "Domain-first, framework-agnostic event system built for Clean Architecture"
version: 1.1.3
homepage: https://github.com/jozzzzep/jozz_events
repository: https://github.com/jozzzzep/jozz_events
issue_tracker: https://github.com/jozzzzep/jozz_events/issues
topics:
  - events
  - clean-architecture
  - domain-driven-design
  - separation-of-concerns
  - bloc

environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:

dev_dependencies:
  lints: ^5.1.1
  test: ^1.24.0
